### ISSUE TITLE
windows 11 is showing error while running setup.exe Bug: 

### ISSUE THREAD

**Issue by Vikaash301** [djthegr8/ZoomAutoJoin#6]
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows, MacOS or Linux]
 - OS Version [e.g. Catalina]

**Additional context**
PLATFORM VERSION INFO
	Windows 			: 10.0.22000.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4341.0 built by: NET48REL1LAST_C
	clr.dll 			: 4.8.4420.0 built by: NET48REL1LAST_C
	dfdll.dll 			: 4.8.4341.0 built by: NET48REL1LAST_C
	dfshim.dll 			: 10.0.22000.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/Hello/Downloads/ZoomAutoJoin-1.0.0/ZoomAutoJoin-1.0.0/Installers/Win-x64/ZoomAutoJoin.application
	Application url			: file:///C:/Users/Hello/Downloads/ZoomAutoJoin-1.0.0/ZoomAutoJoin-1.0.0/Installers/Win-x64/Application%20Files/ZoomAutoJoin_1_0_0_0/ZoomAutoJoin.dll.manifest

IDENTITIES
	Deployment Identity		: ZoomAutoJoin.application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=dbf7f4c0d6df646a, processorArchitecture=msil
	Application Identity		: ZoomAutoJoin.exe, Version=1.0.0.0, Culture=neutral, PublicKeyToken=dbf7f4c0d6df646a, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\Hello\Downloads\ZoomAutoJoin-1.0.0\ZoomAutoJoin-1.0.0\Installers\Win-x64\ZoomAutoJoin.application resulted in exception. Following failure messages were detected:
		+ File, ZoomAutoJoin.deps.json, has a different computed hash than specified in manifest.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [10/14/2021 2:32:47 PM] : Activation of C:\Users\Hello\Downloads\ZoomAutoJoin-1.0.0\ZoomAutoJoin-1.0.0\Installers\Win-x64\ZoomAutoJoin.application has started.
	* [10/14/2021 2:32:47 PM] : Processing of deployment manifest has successfully completed.
	* [10/14/2021 2:32:47 PM] : Installation of the application has started.
	* [10/14/2021 2:32:47 PM] : Processing of application manifest has successfully completed.
	* [10/14/2021 2:32:51 PM] : Found compatible runtime version 4.0.30319.
	* [10/14/2021 2:32:51 PM] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [10/14/2021 2:32:56 PM] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- File, ZoomAutoJoin.deps.json, has a different computed hash than specified in manifest.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			at System.Deployment.Application.ComponentVerifier.VerifyComponents()
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by djthegr8** [comment]
Setup.exe may not be the most stable (or up to date) version of the application, so I would really suggest using the zip file.

**Comment by djthegr8** [comment]
Try installing from [here](https://github.com/djthegr8/ZoomAutoJoin/raw/master/publish.zip) for the latest version
